name: "Render Deploy Action - fork"
description: "Trigger a Render service deploy"
inputs:
  service-id:
    description: "ID of the service to deploy"
    required: true
  api-key:
    description: "A Render API key"
    required: true
  wait-for-success:
    description: "Should job wait for deployment to succeed"
    required: false 
runs:
  using: "node20"
  main: "dist/main.js"
